# Generated by Django 5.0.6 on 2024-10-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.CharField(blank=True, max_length=10, null=True)),
                ('intensity', models.IntegerField(default=0)),
                ('sector', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('insight', models.TextField()),
                ('url', models.URLField(max_length=500)),
                ('region', models.CharField(max_length=200)),
                ('start_year', models.CharField(blank=True, max_length=10, null=True)),
                ('impact', models.CharField(blank=True, max_length=50, null=True)),
                ('added', models.CharField(max_length=50)),
                ('published', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=200)),
                ('relevance', models.IntegerField(default=0)),
                ('pestle', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('likelihood', models.IntegerField(default=0)),
            ],
        ),
    ]
